const reviews = [
  {
    id: 1,
    movieId: 1,
    user: "Alex Johnson",
    rating: 5,
    comment: "An absolute masterpiece. The acting and story are unforgettable.",
  },
  {
    id: 2,
    movieId: 1,
    user: "Sarah Lee",
    rating: 4,
    comment: "Loved the film but thought it dragged a little in the middle.",
  },
  {
    id: 3,
    movieId: 2,
    user: "David Kim",
    rating: 3,
    comment: "Good, but not my style. Still worth a watch.",
  },
  {
    id: 4,
    movieId: 3,
    user: "Emily Parker",
    rating: 5,
    comment: "Cinematography was stunning. I was hooked start to finish.",
  },
  {
    id: 5,
    movieId: 2,
    user: "Michael Chen",
    rating: 4,
    comment: "Solid performances all around. Would recommend to friends.",
  },
  {
    id: 6,
    movieId: 4,
    user: "Jessica Williams",
    rating: 5,
    comment: "One of the best films I've seen this year. Powerful message.",
  },
  {
    id: 7,
    movieId: 3,
    user: "Ryan Thompson",
    rating: 2,
    comment: "Overhyped. Didn't live up to the expectations for me.",
  },
  {
    id: 8,
    movieId: 5,
    user: "Olivia Martinez",
    rating: 4,
    comment: "Great character development and unexpected plot twists.",
  },
  {
    id: 9,
    movieId: 6,
    user: "James Wilson",
    rating: 3,
    comment: "Entertaining but forgettable. Good for a casual watch.",
  },
  {
    id: 10,
    movieId: 4,
    user: "Sophia Garcia",
    rating: 5,
    comment: "Emotional rollercoaster. The ending had me in tears.",
  },
  {
    id: 11,
    movieId: 7,
    user: "Ethan Davis",
    rating: 4,
    comment: "Visually impressive with a compelling storyline.",
  },
  {
    id: 12,
    movieId: 5,
    user: "Isabella Rodriguez",
    rating: 3,
    comment: "Enjoyable but the pacing felt uneven at times.",
  },
  {
    id: 13,
    movieId: 8,
    user: "Noah Anderson",
    rating: 5,
    comment: "A modern classic. Everything about this film is perfect.",
  },
  {
    id: 14,
    movieId: 6,
    user: "Mia Thomas",
    rating: 2,
    comment: "Disappointing adaptation of the source material.",
  },
  {
    id: 15,
    movieId: 9,
    user: "Liam Jackson",
    rating: 4,
    comment: "Strong performances elevate this above typical genre fare.",
  },
  {
    id: 16,
    movieId: 7,
    user: "Charlotte White",
    rating: 3,
    comment: "Good concept but execution could have been better.",
  },
  {
    id: 17,
    movieId: 10,
    user: "Benjamin Harris",
    rating: 5,
    comment: "A breathtaking experience from start to finish.",
  },
  {
    id: 18,
    movieId: 8,
    user: "Amelia Martin",
    rating: 4,
    comment: "Thought-provoking and beautifully shot.",
  },
  {
    id: 19,
    movieId: 9,
    user: "Lucas Clark",
    rating: 2,
    comment: "Not my cup of tea. Found it rather boring honestly.",
  },
  {
    id: 20,
    movieId: 11,
    user: "Harper Lewis",
    rating: 5,
    comment: "Instant classic! Will be rewatching this many times.",
  },
  {
    id: 21,
    movieId: 10,
    user: "Henry Walker",
    rating: 4,
    comment: "Great direction and standout performances by the cast.",
  },
  {
    id: 22,
    movieId: 12,
    user: "Evelyn Hall",
    rating: 3,
    comment: "Decent but nothing special. Middle of the road.",
  },
  {
    id: 23,
    movieId: 11,
    user: "Alexander Young",
    rating: 5,
    comment: "Exceeded all my expectations. A true cinematic achievement.",
  },
  {
    id: 24,
    movieId: 13,
    user: "Ava King",
    rating: 4,
    comment: "Well-crafted with attention to detail in every scene.",
  },
  {
    id: 25,
    movieId: 12,
    user: "William Wright",
    rating: 2,
    comment:
      "The script needed more work. Good actors wasted on weak material.",
  },
  {
    id: 26,
    movieId: 14,
    user: "Sofia Scott",
    rating: 5,
    comment: "Powerful and moving. Left the theater speechless.",
  },
  {
    id: 27,
    movieId: 13,
    user: "Daniel Green",
    rating: 3,
    comment: "Enjoyable enough but didn't leave a lasting impression.",
  },
  {
    id: 28,
    movieId: 15,
    user: "Ella Adams",
    rating: 4,
    comment: "Creative storytelling with memorable characters.",
  },
  {
    id: 29,
    movieId: 14,
    user: "Jackson Baker",
    rating: 5,
    comment: "A perfect blend of action, drama, and heart.",
  },
  {
    id: 30,
    movieId: 15,
    user: "Scarlett Nelson",
    rating: 3,
    comment: "Good ideas but the execution was somewhat lacking.",
  },
];

export default reviews;
